<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Chat.Application\Chat.Application.csproj" />
    <ProjectReference Include="..\Chat.Domain\Chat.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.*" />
  </ItemGroup>
</Project>
