namespace Chat.Domain.Enums;

/// <summary>
/// Indicates the role of a chat message sender.
/// </summary>
public enum MessageRole
{
    /// <summary>The message was sent by the user.</summary>
    User,

    /// <summary>The message was generated by the assistant.</summary>
    Assistant
}
